### ISSUE TITLE
Move to sashabaranov/go-gpt3

### ISSUE THREAD

**Issue by kkdai** [kkdai/chatgpt#10]
**Consideration:**

- sashabaranov/go-gpt3 provides better complete function stability

**Wait** 

- sashabaranov/go-gpt3 is going to provide streaming https://github.com/sashabaranov/go-gpt3/pull/54

**Comment by fastfading** [comment]
这个有什么用， 我看已经merge 了， 可以用了。

**Comment by selsAT** [comment]
我真的很想帮忙，但请翻译你的答案

**Comment by kkdai** [comment]
It is just change source package repo.
Because https://github.com/sashabaranov/go-gpt3 seems more update and more promises.
I will update this PR seems original one already merge.
